name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install
      working-directory: ./  # <-- change this to your folder if package.json is not in root

    - name: Run Webpack
      run: npx webpack
      working-directory: ./  # <-- same folder as above 
      git add .github/workflows/main.yml
git commit -m "Fix GitHub Actions workflow path for package.json"
git push
